/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StudentRegistrationForm;

// import packages first

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;

/**
 *
 * @author Peter
 */
public class StudentRegistrationForm extends javax.swing.JFrame {
    
    // Initialize Variable for our Connection
    
    private static final String username = "PeterVillanueva"; // Our Username
    private static final String password = "villanueva12345"; // Our Password
    private static final String dataConn = "jdbc:mysql://localhost/student_registration"; // Our connection
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;
    

    /**
     * Creates new form StudentRegistrationForm
     */
    public StudentRegistrationForm() {
        initComponents();
    }
    
    // Function Start
    
    public void updateDB(){
        
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver"); // Our MySQL Connector
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("SELECT * FROM class_persons");
            
            rs = pst.executeQuery();
            
            ResultSetMetaData StData = rs.getMetaData();
            
            q = StData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                
                Vector columnData = new Vector();
                for (i = 1; i <= q; i++){
                    columnData.add(rs.getInt("id"));
                    columnData.add(rs.getString("StudentID"));
                    columnData.add(rs.getString("FirstName"));
                    columnData.add(rs.getString("LastName"));
                    columnData.add(rs.getString("Address"));
                    columnData.add(rs.getString("ContactNumber"));
                    columnData.add(rs.getString("DateRegistered"));
                }
                
                RecordTable.addRow(columnData);
            }
                       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }
    
    // Function End

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtDateRegistered = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtContactNumber = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnAdd2 = new javax.swing.JButton();
        btnAdd3 = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 5, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JetBrains Mono Medium", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Student Registration");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1260, 120));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 5, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 5, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 140, 250, 500));

        jLabel2.setFont(new java.awt.Font("JetBrains Mono NL Medium", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Student ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        txtStudentID.setFont(new java.awt.Font("JetBrains Mono Medium", 1, 18)); // NOI18N
        jPanel2.add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 480, 40));

        jLabel3.setFont(new java.awt.Font("JetBrains Mono NL Medium", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("First Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        txtFirstName.setFont(new java.awt.Font("JetBrains Mono Medium", 1, 18)); // NOI18N
        jPanel2.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 480, 40));

        jLabel4.setFont(new java.awt.Font("JetBrains Mono NL Medium", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Last Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        txtLastName.setFont(new java.awt.Font("JetBrains Mono Medium", 1, 18)); // NOI18N
        jPanel2.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 480, 40));

        txtDateRegistered.setFont(new java.awt.Font("JetBrains Mono Medium", 1, 18)); // NOI18N
        jPanel2.add(txtDateRegistered, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 480, 40));

        jLabel5.setFont(new java.awt.Font("JetBrains Mono NL Medium", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Date Registered");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        txtContactNumber.setFont(new java.awt.Font("JetBrains Mono Medium", 1, 18)); // NOI18N
        jPanel2.add(txtContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 480, 40));

        txtAddress.setFont(new java.awt.Font("JetBrains Mono Medium", 1, 18)); // NOI18N
        jPanel2.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 480, 40));

        jLabel6.setFont(new java.awt.Font("JetBrains Mono NL Medium", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Contact Number");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("JetBrains Mono NL Medium", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Address");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTable1.setFont(new java.awt.Font("JetBrains Mono Medium", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "StudentID", "FirstName", "LastName", "Address", "ContactNumber", "DateRegistered"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 740, 170));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1000, 500));

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 5, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 102, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 5, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 140, 250, 500));

        btnUpdate.setFont(new java.awt.Font("JetBrains Mono NL Medium", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 230, 60));

        btnAdd.setFont(new java.awt.Font("JetBrains Mono NL Medium", 1, 18)); // NOI18N
        btnAdd.setText("Add New");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel4.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 60));

        jPanel6.setBackground(new java.awt.Color(0, 102, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 5, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 102, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 5, true));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 140, 250, 500));

        btnAdd2.setFont(new java.awt.Font("JetBrains Mono NL Medium", 1, 18)); // NOI18N
        btnAdd2.setText("Add New");
        btnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 230, 60));

        btnAdd3.setFont(new java.awt.Font("JetBrains Mono NL Medium", 1, 18)); // NOI18N
        btnAdd3.setText("Add New");
        btnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd3ActionPerformed(evt);
            }
        });
        jPanel6.add(btnAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 60));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 140, 250, 500));

        btnReset.setFont(new java.awt.Font("JetBrains Mono NL Medium", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel4.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 230, 60));

        btnPrint.setFont(new java.awt.Font("JetBrains Mono NL Medium", 1, 18)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel4.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 230, 60));

        btnDelete.setFont(new java.awt.Font("JetBrains Mono NL Medium", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 230, 60));

        btnExit.setFont(new java.awt.Font("JetBrains Mono NL Medium", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel4.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 230, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 140, 250, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int selectedRows = jTable1.getSelectedRow();
        
        try {
            
            id = Integer.parseInt(RecordTable.getValueAt(selectedRows, 0).toString());
            Class.forName("com.mysql.cj.jdbc.Driver"); // Our MySQL Connector
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("UPDATE class_persons SET StudentID =?, FirstName =?, LastName =?,"
                    + "Address =?, ContactNumber =?, DateRegistered =? WHERE id =?");
            
            pst.setString(1, txtStudentID.getText());
            pst.setString(2, txtFirstName.getText());
            pst.setString(3, txtLastName.getText());
            pst.setString(4, txtAddress.getText());
            pst.setString(5, txtContactNumber.getText());
            pst.setString(6, txtDateRegistered.getText());
            pst.setInt(7, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Student Record Updated");
            updateDB();
            
        } catch (ClassNotFoundException e) {
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, e);
        } catch (SQLException ex){
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver"); // Our MySQL Connector
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("INSERT INTO class_persons(StudentID, FirstName, LastName, "
                    + "Address, ContactNumber, DateRegistered)value(?,?,?,?,?,?)");
            
            pst.setString(1, txtStudentID.getText());
            pst.setString(2, txtFirstName.getText());
            pst.setString(3, txtLastName.getText());
            pst.setString(4, txtAddress.getText());
            pst.setString(5, txtContactNumber.getText());
            pst.setString(6, txtDateRegistered.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Student Record Added");
            updateDB();
            
        } catch (ClassNotFoundException e) {
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, e);
        } catch (SQLException ex){
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd2ActionPerformed

    private void btnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd3ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtStudentID.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtAddress.setText("");
        txtContactNumber.setText("");
        txtDateRegistered.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat Header = new MessageFormat("Printing in Progress");
        MessageFormat Footer = new MessageFormat("Page {0, number, integer}");
        
        try {
            jTable1.print(JTable.PrintMode.NORMAL,Header, Footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("No Printer Found", e);
        }
        
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int selectedRows = jTable1.getSelectedRow();
        
        try {
            
            id = Integer.parseInt(RecordTable.getValueAt(selectedRows, 0).toString());
            deleteItem = JOptionPane.showConfirmDialog(null, "Confirm if you want to Delete Data", 
                    "Warning", JOptionPane.YES_OPTION);
            if(deleteItem == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.cj.jdbc.Driver"); // Our MySQL Connector
                sqlConn = DriverManager.getConnection(dataConn, username, password);
                pst = sqlConn.prepareStatement("DELETE FROM class_persons WHERE id =?");
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Updated");
                updateDB();
            
                txtStudentID.setText("");
                txtFirstName.setText("");
                txtLastName.setText("");
                txtAddress.setText("");
                txtContactNumber.setText("");
                txtDateRegistered.setText("");
            }
            
        } catch (ClassNotFoundException e) {
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, e);
        } catch (SQLException ex){
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
            
        }
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed
private JFrame frame;
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", 
                "Student Registration Form", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int selectedRows = jTable1.getSelectedRow();
        
        txtStudentID.setText(RecordTable.getValueAt(selectedRows, 1).toString());
        txtFirstName.setText(RecordTable.getValueAt(selectedRows, 2).toString());
        txtLastName.setText(RecordTable.getValueAt(selectedRows, 3).toString());
        txtAddress.setText(RecordTable.getValueAt(selectedRows, 4).toString());
        txtContactNumber.setText(RecordTable.getValueAt(selectedRows, 5).toString());
        txtDateRegistered.setText(RecordTable.getValueAt(selectedRows, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    
    private void forWindowActivated(java.awt.event.WindowEvent evt){
        updateDB();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnAdd3;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtDateRegistered;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration//GEN-END:variables
}
